version: '3'
services:
    py3s:
        restart: always
        build: .
        container_name: 'py3flask'
        working_dir: '/root/work'
        tty: true
        volumes:
            - .:/root/work
            - ~/.ssh/id_rsa:/root/.ssh/id_rsa
        environment:
            - "TZ=Asia/Tokyo"
        ports:
            - "5000:5000"
